export enum ErrorCode {
    BAD_REQUEST = "BAD_REQUEST",
    UNAUTHORIZED = "UNAUTHORIZED",
    FORBIDDEN = "FORBIDDEN",
    NOT_FOUND = "NOT_FOUND",
    CONFLICT = "CONFLICT",
    INTERNAL = "INTERNAL_ERROR",
  
    EVENT_NOT_FOUND = "EVENT_NOT_FOUND",
    USER_NOT_FOUND = "USER_NOT_FOUND",
    INVALID_TIME_RANGE = "INVALID_TIME_RANGE",
    CAPACITY_FULL = "CAPACITY_FULL",
    ALREADY_RSVPED = "ALREADY_RSVPED",
  }
  